import { useEffect, useMemo, useState } from 'react'
import * as THREE from 'three'

// Measured against the authored poster_frame opening (not its outside rails):
// the usable portrait aperture is 0.66m × 0.96m at the frame's native scale.
// The print fills that aperture; any remaining pixels are matte generated by
// textureFromImage below, never a second decorative border.
const POSTER_WIDTH = .66
const POSTER_HEIGHT = .96
const POSTER_TEXTURE_WIDTH = 560
const POSTER_TEXTURE_HEIGHT = 920

export function textureFromImage(image) {
  const width = image.naturalWidth || image.width
  const height = image.naturalHeight || image.height
  // Render into a fixed frame-sized canvas.  The source is contained (never
  // stretched) and the unused area is deliberate black letterbox/pillarbox.
  // This also makes the result deterministic for every poster aspect ratio.
  const canvas = document.createElement('canvas')
  canvas.width = POSTER_TEXTURE_WIDTH
  canvas.height = POSTER_TEXTURE_HEIGHT
  const context = canvas.getContext('2d')
  // The matte is part of the print, not a translucent frame/glass surface.
  // Keep it true black so aspect-ratio padding reads as a deliberate premium
  // letterbox rather than the grey cast produced by the old overlay plane.
  context.fillStyle = '#000000'
  context.fillRect(0, 0, canvas.width, canvas.height)
  const fit = Math.min(canvas.width / width, canvas.height / height)
  const drawWidth = Math.max(1, Math.round(width * fit))
  const drawHeight = Math.max(1, Math.round(height * fit))
  context.drawImage(image, Math.round((canvas.width - drawWidth) / 2), Math.round((canvas.height - drawHeight) / 2), drawWidth, drawHeight)
  const texture = new THREE.CanvasTexture(canvas)
  texture.colorSpace = THREE.SRGBColorSpace
  texture.anisotropy = 8
  texture.minFilter = THREE.LinearFilter
  texture.magFilter = THREE.LinearFilter
  texture.generateMipmaps = false
  texture.needsUpdate = true
  return texture
}

export function PosterPrint({ placement, url }) {
  const [texture, setTexture] = useState(null)
  useEffect(() => {
    let disposed = false
    const image = new Image()
    image.crossOrigin = 'anonymous'
    image.onload = () => {
      if (disposed) return
      try {
        setTexture(previous => {
          previous?.dispose()
          return textureFromImage(image)
        })
      } catch {
        setTexture(current => { current?.dispose(); return null })
      }
    }
    image.onerror = () => { if (!disposed) setTexture(current => { current?.dispose(); return null }) }
    image.src = url
    return () => { disposed = true; setTexture(current => { current?.dispose(); return null }) }
  }, [url])
  const p = placement.transform?.position || {}
  const r = placement.transform?.rotation || {}
  return <group position={[p.x || 0, p.y || 0, p.z || 0]} rotation={[r.x || 0, r.y || 0, r.z || 0]}>
    {/* The clear face is removed from the authored poster asset. This plane is
        exactly the inner opening, with only a tiny depth offset to sit behind
        the frame rails. */}
    <mesh position={[0, 0, .012]} renderOrder={3}>
      <planeGeometry args={[POSTER_WIDTH, POSTER_HEIGHT]} />
      {texture
        ? <meshBasicMaterial map={texture} toneMapped={false} side={THREE.DoubleSide} />
        : <meshBasicMaterial color="#1a1520" toneMapped={false} side={THREE.DoubleSide} />}
    </mesh>
  </group>
}

export default function RoomPosterDisplays({ bootstrap, activeInstanceId = null }) {
  const posters = useMemo(() => (bootstrap?.room?.placements || []).map(row => {
    if (row.instance_id === activeInstanceId) return null
    const instance = bootstrap?.owned_instances?.find(value => value.id === row.instance_id)
    const definition = bootstrap?.catalog?.find(value => value.id === instance?.definition_id)
    if (definition?.asset_id !== 'poster_frame') return null
    const imageId = row.transform?.content?.image_id
    if (!imageId) return null
    return { row, url: `/api/images/${imageId}/preview?w=720`, imageId }
  }).filter(Boolean), [activeInstanceId, bootstrap])
  return <group name="vault-posters">
    {posters.map(item => <PosterPrint key={`${item.row.instance_id}-${item.imageId}`} placement={item.row} url={item.url} />)}
  </group>
}
